
services:
  zookeeper:
    image: zookeeper:3.9
    container_name: url-shortener-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - url-shortener-zookeeper-data:/data
      - url-shortener-zookeeper-datalog:/datalog
      - url-shortener-zookeeper-logs:/logs
    networks:
      - url-shortener-network

  redis:
    image: redis:7-alpine
    container_name: url-shortener-redis
    ports:
      - "6379:6379"
    volumes:
      - url-shortener-redis-data:/data
    networks:
      - url-shortener-network
    command: redis-server --appendonly yes

volumes:
  url-shortener-zookeeper-data:
    name: url-shortener-zookeeper-data
  url-shortener-zookeeper-datalog:
    name: url-shortener-zookeeper-datalog
  url-shortener-zookeeper-logs:
    name: url-shortener-zookeeper-logs
  url-shortener-redis-data:
    name: url-shortener-redis-data

networks:
  url-shortener-network:
    driver: bridge

